service: file-uploader-v2
image: and0333/file_uploader_v2


env:
  secret:
    - SECRET_KEY_BASE
    - RAILS_MASTER_KEY
    - DATABASE_PASSWORD
  clear:
    RAILS_ENV: "${RAILS_ENV}"
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
    DATABASE_HOST: "${DATABASE_HOST}"
    DATABASE_PORT: 5432
    DATABASE_NAME: "${DATABASE_NAME}"
    DATABASE_USER: "${DATABASE_USER}"

servers:
  web:
    hosts:
      #- 10.211.55.100 # локальный сервер
      - 185.193.90.91  # выданный сервер


# Docker registry
registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD



# SSH настройки
ssh:
  user: ingipro
  port: 22122
  keys:
    - ~/.ssh/ingipro_ed25519

# PostgreSQL как accessory
accessories:
  db:
    image: postgres:17-alpine
    #host: 10.211.55.100
    host: 185.193.90.91

    env:
      clear:
        POSTGRES_DB: "${DATABASE_NAME}"
        POSTGRES_USER: "${DATABASE_USER}"
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Volumes
volumes:
  - postgres_data


builder:
  #arch: arm64 #для моего локального сервера
  arch: amd64 # выданный сервер


aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
